### ISSUE TITLE
Project initiation tasks for postpartum LARC project

### ISSUE THREAD

**Issue by rileeki** [orchid-initiative/postpartum-larc#1]
- [x] Review the Project Plan Template in the Orchid Google Drive. Make a copy of it in the LARC project folder.
- [x]  Meet with the project sponsors
- [x] **Monday 12/18: Set up a GitHub project in the [LARC repo](https://github.com/orchid-initiative/postpartum-larc)**
- [x] **Monday 12/18: Fill in all the links in the project plan.  (It's fine if some of the documents it points to are still blank.)**
- [x] **Monday 12/18: Draft the project charter and send to Riley & Jen for feedback** (email & link)
   - [x] Update the GitHub repository project charter
- [x]  **Monday 12/18: Work with Riley to identify all the stakeholders**
   - [x] Review stakeholder coursera modula
   - [x] Share what you've learned about project roles and make sure we're filling them & documenting expectations.
- [x]  **Monday 12/18: Schedule stakeholder interviews**
   - [x] Jen Franks
   - [x] Riley Kwong
   - [x] Rhonda Tullis
   - [x] Jim Cheairs
- [x] Get feedback from all stakeholders on the project plan and project charter
   - [x] Rhonda
   - [x] Jim
   - [x] Riley
- [x] Finalize the project charter & project plan
- [x] Schedule the kick-off call!

**Comment by IrisFleischer** [comment]
Project roles will vary depending on the needs of the project. We should focus on filling the roles we need, then reassessing. Further stakeholder interviews and a proper stakeholder analysis will be done after this initial recruitment period.

**Comment by IrisFleischer** [comment]
This project is too small to effectively utilize a RACI chart, so I removed the bullet point
